routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::get('/contacts', function() {
  $id = 1;
  $contacts = \App\Contacts::find($id);

  return view('contacts.index', compact('contacts'));

});

Route::get('/', 'MeniuController@index');

Route::resource('dishes', 'DishController');
// Route::resource('/meniu', 'MeniuController@index');
Route::resource('user', 'UserController');
Route::resource('cart', 'CartController');
Route::resource('meniu', 'MeniuController');
Route::resource('orderform', 'OrderFormController');
Route::resource('payment', 'PaymentController');
Route::resource('checkout', 'CheckoutController');


Route::post('cart', 'CartController@store')->name('cart.store');
Route::post('cartDestroyAll', 'CartController@destroyAll')->name('cart.destroyAll');
Route::post('cartDestroy', 'CartController@destroy')->name('cart.destroy');

app/Meniu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meniu extends Model
{
    public function dishes() {

    	return $this->hasMany('App\Dish');
    }
}

app/Http/Controllers/MeniuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;


class MeniuController extends Controller
{   

    public function __construct ()
    {

        // $this->middleware('auth', ['only' => 'create']);
        $this->middleware('auth', ['except' => ['index', 'show']]);

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menius = \App\Meniu::all();
        foreach ($menius as $meniu) {
            $meniu["dishes"] = \App\Dish::where('meniu_id', $meniu->id)->limit(3)->get();
        }
        

        return view('meniu.index', compact('menius'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $success = \App\Meniu::create($request->all());
        return redirect()->route('meniu.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   //gaunamm visus meniu irasus
        $meniu = \App\Meniu::find($id);

        // gautu patiekalus pagal kategorija
        $dishes = \App\Dish::where('meniu_id', $id)->get();
        // atvaizduojam
        return view('meniu.show', compact('meniu', 'dishes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Meniu/create.blade.php
@extends('main')

@section('content')



@endsection

resources/views/Meniu/index.blade.php
@extends('main')

@section('content')
<div class="row">
	<div class="col-md-12">
        <h1>Le Bon Crubeen</h1>
		<div class="row carousel-holder">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="{{ asset('img/slider1.jpg') }}" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="{{ asset('img/slider2.jpg') }}" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="{{ asset('img/slider3.jpg') }}" alt="">
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
      </div>
</div>
<a href="{{ route('dishes.create') }}" class="btn btn-info">Add dish</a>
<a href="{{ route('user.index') }}" class="btn btn-info">View users</a>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
            @foreach ($menius as $index => $menu)
            <h3>
                <a href="{{ route('meniu.show', $menu->id) }}">{{ $menu->title }}</a>
            </h3>
                @foreach($menu["dishes"] as $dish)
                
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="thumbnail">
                     <a href="{{ route('dishes.show', $dish->id) }}"><img src="{{ $dish->photo }}" alt=""></a>
                     <div class="caption">
                        <h4 class="pull-right">{{$dish->price}}  €</h4>
                        <h4><a href="{{ route('dishes.show', $dish->id) }}">{{ $dish->title }}</a></h4>
                        <p>{{substr($dish->description, 0, 50)}}</p>
                    </div>
                    <a href="{{ route('dishes.edit', $dish->id) }}" width="200px" class="btn btn-success btn-edit">EDIT</a>
                    <a  data-dish-id="{{ $dish->id }}" name="stay_here" href="#stay_here" width="100px" class="btn btn-success add-to-cart btn-edit">Add to cart</a>    
                    </div>
                </div>

                @if(++$index % 4 == 0)
                    </div><div class="row">
                @endif

                @endforeach
        @endforeach
    </div>
</div>
  
@endsection

resources/views/Meniu/show.blade.php
@extends('main')

@section('content')

<h1>Meniu</h1>

<div class="row">

@foreach($dishes as $index => $dish)
<div class="col-md-4 col-sm-6 col-xs-12">
    <div class="thumbnail">
       <a href="{{ route('dishes.show', $dish->id) }}"><img src="{{ $dish->photo }}" alt=""></a>
       <div class="caption">
            <h4><a href="{{ route('dishes.show', $dish->id) }}">{{ $dish->title }}</a></h4>
            <p>{{$dish->description}}</p>
            <h4 class="pull-right">{{$dish->price}}</h4> 
        </div>
    <a href="{{ route('dishes.edit', $dish->id) }}" width="200px" class="btn btn-success btn-edit">EDIT</a> 
    @if(++$index % 4 == 0)
        </div><div class="row">
    @endif
    </div>
</div>
@endforeach
    
</div>


@endsection