routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::get('/contacts', function() {
  $id = 1;
  $contacts = \App\Contacts::find($id);

  return view('contacts.index', compact('contacts'));

});

Route::get('/', 'MeniuController@index');

Route::resource('dishes', 'DishController');
// Route::resource('/meniu', 'MeniuController@index');
Route::resource('user', 'UserController');
Route::resource('cart', 'CartController');
Route::resource('meniu', 'MeniuController');
Route::resource('orderform', 'OrderFormController');
Route::resource('payment', 'PaymentController');
Route::resource('checkout', 'CheckoutController');


Route::post('cart', 'CartController@store')->name('cart.store');
Route::post('cartDestroyAll', 'CartController@destroyAll')->name('cart.destroyAll');
Route::post('cartDestroy', 'CartController@destroy')->name('cart.destroy');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'surname',
        'birthdate',
        'phone_number',
        'email', 
        'password',
        'address',
        'city',
        'zip_code',
        'country',
        'is_admin'
    ];

     public function cart()
    {
        return $this->hasOne('App\Cart');
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Auth;


use Illuminate\Http\Request;

class UserController extends Controller
{   
    public function __construct ()
    {

        $this->middleware(function($request, $next) {
            if(
                \Auth::guest()
                ||
                (!\Auth::guest() && \Auth::user()->is_admin == 0))
            {
                return redirect()->route('login');
            }

            return $next($request);
        });
        

    }


    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = \App\User::All();
        // var_dump($users);
        
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new \App\User();
        //request nesa reiksmes is title 
        $user->name       = $request->name;
        $user->email    = $request->email;

        $user->save();
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = \App\User::find($id);

        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\User::find($id);

        //var_dump($users);
        return view('user.create', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        
        if(!empty($request->password)){
            // jei password laukas nera tuscias - perrasom masyvo 'password' reiksme su jo pacio reiksme tik uzhashinta
            $data['password'] = \Hash::make($request->password);
        }else{
            // ismetam 'password' key is masyvo, nes kitaip uzsaugotu kaip tuscia password'a
            unset($data['password']);
        }
        
        // atnaujinam user duomenis su modifikuotais duomenimis
        $user = \App\User::find($id)->update($data);

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\User::find($id)->delete();

        return redirect()->route('user.index');
    }
}

resources/views/user/create.blade.php
@extends('main')

@section('content')

<h1>User info page</h1>


	
		
	
@if(isset($user))
{{ Form::open(['route' => ['user.update', $user->id], "method" => "POST"]) }}
	<input type="hidden" name="_method" value="PUT">
@else

{!! Form::open(['url' => '/user', 'id'=>'myRegister', 'method' => "POST"]) !!}
@endif
	{{ Form::label('Name') }}<br>
	@if(isset($user))
		{{ Form::text('name', $user->name, ['class' => 'form-control']) }}
	@else
		{{ Form::text('name','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Surname') }}<br>
	@if(isset($user))
		{{ Form::text('surname', $user->surname, ['class' => 'form-control']) }}
	@else
		{{ Form::text('surname','',['class' => 'form-control']) }}<br>
	@endif
	
	{{ Form::label('Birthdate') }}<br>
	@if(isset($user))
		{{ Form::date('birthdate', $user->birthdate, ['class' => 'form-control']) }}
	@else
		{{ Form::date('birthdate','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Phone Number') }}<br>
	@if(isset($user))
		{{ Form::text('phone_number', $user->phone_number, ['class' => 'form-control']) }}
	@else
		{{ Form::text('phone_number','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Email') }}<br>
	@if(isset($user))
		{{ Form::text('email', $user->email, ['class' => 'form-control']) }}
	@else
		{{ Form::text('email','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Address') }}<br>
	@if(isset($user))
		{{ Form::text('address', $user->address, ['class' => 'form-control']) }}
	@else
		{{ Form::text('address','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('City') }}<br>
	@if(isset($user))
		{{ Form::text('city', $user->city, ['class' => 'form-control']) }}
	@else
		{{ Form::text('city','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Zip Code') }}<br>
	@if(isset($user))
		{{ Form::text('zip_code', $user->zip_code, ['class' => 'form-control']) }}
	@else
		{{ Form::text('zip_code','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Country') }}<br>
	@if(isset($user))
		{{ Form::text('country', $user->country, ['class' => 'form-control']) }}
	@else
		{{ Form::text('country','',['class' => 'form-control']) }}<br>
	@endif

	{{ Form::label('Password') }}<br>
	@if(isset($user))
		{{ Form::text('password','', ['class' => 'form-control']) }}
	@else
		{{ Form::text('password','',['class' => 'form-control']) }}<br>
	@endif

	@if($user->is_admin == 1)
		<input type="hidden" name="is_admin" value="0">
		<input type="checkbox" checked="" name="is_admin" value="1">Admin<br>
	@else
		<input type="hidden" name="is_admin" value="0">
		<input type="checkbox" name="is_admin" value="1">Admin<br>
	@endif

	{!! Form::submit('Submit', ['class' => 'btn btn-warning']); !!}
	{!! Form::close() !!}


@if(isset($user))

{{ Form::open(['route' => ['user.destroy', $user->id], "method" => "POST"]) }}
	<input type="hidden" name="_method" value="DELETE">

	{{ csrf_field() }}

	
	{!! Form::submit('Detele', ['class' => 'btn btn-warning']); !!}
	{!! Form::close() !!}

@endif




@endsection

resources/views/user/index.blade.php
@extends('main')

@section('content')

<h3>Users info</h3>
	
<table>
	<tr>
		<th>Name</th>
		<th>Surname</th>
		<th>Birthdate</th>
		<th>Phone Number</th>
		<th>Email</th>
		<th>Address</th>
		<th>City</th>
		<th>Zip Code</th>
		<th>Country</th>
		<th>Admin</th>
		<th></th>
	</tr>
	@foreach($users as $user)
	<tr>
		<td>{{ $user->name }}</td>
		<td>{{ $user->surname }}</td>
		<td>{{ $user->birthdate }}</td>
		<td>{{ $user->phone_number }}</td>
		<td>{{ $user->email }}</td>
		<td>{{ $user->address }}</td>
		<td>{{ $user->city }}</td>
		<td>{{ $user->zip_code }}</td>
		<td>{{ $user->country }}</td>
		<td>{{ $user->is_admin }}</td>
		@if(Auth::guest())

		@else
		<td><a href="{{ route('user.edit', $user->id) }}" class="btn btn-success">Edit</a></td>
		@endif
	</tr>
	@endforeach 
</table>


@endsection